# Generated by Django 5.1.2 on 2025-07-05 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('is_liked', models.BooleanField(default=False, verbose_name='いいね')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.postfood', verbose_name='食材')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_reviews', to=settings.AUTH_USER_MODEL, verbose_name='レビューワー')),
            ],
            options={
                'verbose_name': '食材レビュー',
                'verbose_name_plural': '食材レビュー',
                'db_table': 'food_review',
                'ordering': ['-created_at'],
                'unique_together': {('food', 'reviewer')},
            },
        ),
    ]
