# Generated by Django 5.1.2 on 2025-07-05 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodreview',
            name='is_liked',
        ),
        migrations.AlterField(
            model_name='foodreview',
            name='comment',
            field=models.TextField(verbose_name='コメント'),
        ),
        migrations.CreateModel(
            name='FoodLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='いいね日時')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='stores.postfood', verbose_name='食材')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_likes', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '食材いいね',
                'verbose_name_plural': '食材いいね',
                'db_table': 'food_like',
                'ordering': ['-created_at'],
                'unique_together': {('food', 'user')},
            },
        ),
    ]
