# Generated by Django 5.1.2 on 2025-06-27 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
                ('color', models.CharField(default='#6c757d', help_text='HEXカラーコード（例: #28a745）', max_length=7, verbose_name='タグカラー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'db_table': 'post_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PostFood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='食材名')),
                ('description', models.TextField(blank=True, verbose_name='食材の説明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/', verbose_name='画像')),
                ('use_date', models.DateField(verbose_name='使用期限')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(choices=[('kg', 'キログラム'), ('g', 'グラム'), ('L', 'リットル'), ('ml', 'ミリリットル'), ('個', '個'), ('袋', '袋'), ('箱', '箱'), ('本', '本'), ('枚', '枚'), ('束', '束'), ('パック', 'パック'), ('その他', 'その他')], default='個', max_length=10, verbose_name='単位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('store_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_foods', to=settings.AUTH_USER_MODEL, verbose_name='店舗アカウント')),
                ('tags', models.ManyToManyField(blank=True, to='stores.posttags', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '食材',
                'verbose_name_plural': '食材',
                'db_table': 'post_food',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='関連付け日時')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.postfood', verbose_name='食材')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.posttags', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '食材タグ関連',
                'verbose_name_plural': '食材タグ関連',
                'db_table': 'post_tagging',
                'unique_together': {('food', 'tag')},
            },
        ),
    ]
